/**
 * @file Defines standard eslint rules.
 * @author Matt Rinker
 */

/* eslint-disable no-magic-numbers */
module.exports = {
  'accessor-pairs': ['error', { enforceForClassMembers: true }],
  'array-bracket-newline': ['error', { multiline: true }],
  'array-bracket-spacing': 'error',
  'array-callback-return': 'error',
  'array-element-newline': ['error', 'consistent'],
  'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
  'arrow-parens': 'error',
  'arrow-spacing': 'error',
  'block-scoped-var': 'error',
  'block-spacing': 'error',
  'brace-style': ['error', '1tbs'],
  'camelcase': 'error',
  'capitalized-comments': 'off',
  'class-methods-use-this': 'error',
  'comma-dangle': ['error', 'always-multiline'],
  'comma-spacing': 'error',
  'comma-style': 'error',
  'complexity': ['error', 15],
  'computed-property-spacing': 'error',
  'consistent-return': 'error',
  'consistent-this': 'error',
  'constructor-super': 'error',
  'curly': ['error', 'all'],
  'default-case': ['error', { commentPattern: '^skip\\sdefault' }],
  'default-case-last': 'error',
  'default-param-last': 'error',
  'dot-location': ['error', 'property'],
  'dot-notation': 'error',
  'eol-last': 'error',
  'eqeqeq': 'error',
  'for-direction': 'error',
  'func-call-spacing': 'error',
  'func-name-matching': 'error',
  'func-names': 'off',
  'func-style': ['error', 'expression'],
  'function-call-argument-newline': ['error', 'consistent'],
  'function-paren-newline': ['error', 'multiline-arguments'],
  'generator-star-spacing': [
    'error', {
      after: true,
      before: false,
    },
  ],
  'getter-return': 'error',
  'grouped-accessor-pairs': ['error', 'getBeforeSet'],
  'guard-for-in': 'error',
  'id-length': ['error', { min: 3 }],
  'implicit-arrow-linebreak': 'error',
  'indent': ['error', 2],
  'init-declarations': 'off',

  'jsx-quotes': ['error', 'prefer-single'],
  'key-spacing': 'error',
  'keyword-spacing': 'error',
  'line-comment-position': 'off',
  'linebreak-style': 'error',
  'lines-around-comment': [
    'error', {
      afterBlockComment: true,
      allowArrayEnd: false,
      allowArrayStart: true,
      allowBlockEnd: false,
      allowBlockStart: true,
      allowClassEnd: false,
      allowClassStart: true,
      allowObjectEnd: false,
      allowObjectStart: true,
      beforeBlockComment: true,
      beforeLineComment: true,
    },
  ],
  'lines-between-class-members': 'error',
  'max-classes-per-file': 'error',
  'max-depth': ['error', 4],
  'max-len': [
    'error', {
      code: 110,
      ignoreComments: true,
      ignoreRegExpLiterals: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreTrailingComments: true,
      ignoreUrls: true,
      tabWidth: 2,
    },
  ],
  'max-lines': [
    'error', {
      max: 500,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  'max-lines-per-function': [
    'error', {
      max: 50,
      skipBlankLines: true,
      skipComments: true,
    },
  ],
  'max-nested-callbacks': ['error', { max: 3 }],
  'max-params': ['error', { max: 5 }],
  'max-statements': 'off',
  'max-statements-per-line': ['error', { max: 1 }],
  'multiline-comment-style': ['error', 'starred-block'],
  'multiline-ternary': 'off',
  'new-cap': 'error',
  'new-parens': 'error',
  'newline-per-chained-call': ['error', { ignoreChainWithDepth: 2 }],
  'no-alert': 'error',
  'no-array-constructor': 'error',
  'no-async-promise-executor': 'error',
  'no-await-in-loop': 'off',
  'no-bitwise': 'warn',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-class-assign': 'error',
  'no-compare-neg-zero': 'error',
  'no-cond-assign': 'error',
  'no-confusing-arrow': 'error',
  'no-console': ['error', { allow: ['error', 'info', 'warn'] }],
  'no-const-assign': 'error',
  'no-constant-condition': 'error',
  'no-constructor-return': 'error',
  'no-continue': 'warn',
  'no-control-regex': 'warn',
  'no-debugger': 'error',
  'no-delete-var': 'error',
  'no-div-regex': 'error',
  'no-dupe-args': 'error',
  'no-dupe-class-members': 'error',
  'no-dupe-else-if': 'error',
  'no-dupe-keys': 'error',
  'no-duplicate-case': 'error',
  'no-duplicate-imports': 'error',
  'no-else-return': 'error',
  'no-empty': 'error',
  'no-empty-character-class': 'error',
  'no-empty-function': 'warn',
  'no-empty-pattern': 'error',
  'no-eq-null': 'error',
  'no-eval': 'error',
  'no-ex-assign': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-boolean-cast': 'error',
  'no-extra-label': 'error',
  'no-extra-parens': [
    'error', 'all', {
      enforceForArrowConditionals: false,
      enforceForFunctionPrototypeMethods: false,
      enforceForNewInMemberExpressions: false,
      enforceForSequenceExpressions: false,
      ignoreJSX: 'multi-line',
      nestedBinaryExpressions: false,
    },
  ],
  'no-extra-semi': 'error',
  'no-fallthrough': ['error', { commentPattern: 'falls?\\s*through' }],
  'no-floating-decimal': 'error',
  'no-func-assign': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': ['error', { 'boolean': false }],
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-import-assign': 'error',
  'no-inline-comments': 'off',
  'no-inner-declarations': ['error', 'both'],
  'no-invalid-regexp': 'error',
  'no-invalid-this': 'error',
  'no-irregular-whitespace': [
    'error', {
      skipComments: true,
      skipRegExps: true,
      skipStrings: true,
      skipTemplates: true,
    },
  ],
  'no-iterator': 'error',
  'no-label-var': 'error',
  'no-labels': 'off',
  'no-lone-blocks': 'error',
  'no-lonely-if': 'error',
  'no-loop-func': 'error',
  'no-loss-of-precision': 'warn',
  'no-magic-numbers': [
    'warn', {
      ignore: [1, 24, 60, 365, 1000],
      ignoreArrayIndexes: true,
      ignoreDefaultValues: true,
    },
  ],
  'no-misleading-character-class': 'error',
  'no-mixed-operators': 'error',
  'no-mixed-spaces-and-tabs': ['error', 'smart-tabs'],
  'no-multi-assign': 'error',
  'no-multi-spaces': 'error',
  'no-multi-str': 'error',
  'no-multiple-empty-lines': ['error', { max: 1 }],
  'no-negated-condition': 'error',
  'no-nested-ternary': 'off', // use unicorn/no-nested-ternary instead
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-object': 'error',
  'no-new-symbol': 'error',
  'no-new-wrappers': 'error',
  'no-nonoctal-decimal-escape': 'error',
  'no-obj-calls': 'error',
  'no-octal': 'error',
  'no-octal-escape': 'error',
  'no-param-reassign': 'warn',
  'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
  'no-promise-executor-return': 'error',
  'no-proto': 'error',
  'no-prototype-builtins': 'error',
  'no-redeclare': 'error',
  'no-regex-spaces': 'error',
  'no-restricted-globals': 'off',
  'no-return-assign': ['error', 'always'],
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-setter-return': 'error',
  'no-shadow': 'off',
  'no-shadow-restricted-names': 'error',
  'no-sparse-arrays': 'error',
  'no-tabs': 'error',
  'no-template-curly-in-string': 'error',
  'no-ternary': 'off',
  'no-this-before-super': 'error',
  'no-throw-literal': 'error',
  'no-trailing-spaces': ['error', { ignoreComments: true }],
  'no-undef': ['error', { 'typeof': true }],
  'no-undef-init': 'error',
  'no-underscore-dangle': [
    'error', {
      allowAfterSuper: true,
      allowAfterThis: true,
      allowAfterThisConstructor: true,
      allowFunctionParams: false,
      enforceInMethodNames: true,
    },
  ],
  'no-unexpected-multiline': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unneeded-ternary': ['error', { defaultAssignment: false }],
  'no-unreachable': 'error',
  'no-unreachable-loop': 'error',
  'no-unsafe-finally': 'error',
  'no-unsafe-negation': 'error',
  'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-unused-vars': [
    'error', {
      args: 'after-used',
      caughtErrors: 'none',
      ignoreRestSiblings: true,
    },
  ],
  'no-use-before-define': [
    'error', {
      classes: true,
      functions: true,
    },
  ],
  'no-useless-backreference': 'error',
  'no-useless-call': 'error',
  'no-useless-catch': 'error',
  'no-useless-computed-key': ['error', { enforceForClassMembers: true }],
  'no-useless-concat': 'error',
  'no-useless-constructor': 'error',
  'no-useless-escape': 'error',
  'no-useless-rename': [
    'error', {
      ignoreDestructuring: true,
      ignoreExport: true,
      ignoreImport: true,
    },
  ],
  'no-useless-return': 'error',
  'no-var': 'error',
  'no-void': 'error',
  'no-warning-comments': 'warn',
  'no-whitespace-before-property': 'error',
  'no-with': 'error',
  'nonblock-statement-body-position': ['error', 'beside'],
  'object-curly-newline': [
    'error', {
      minProperties: 2,
      multiline: true,
    },
  ],
  'object-curly-spacing': ['error', 'always'],
  'object-property-newline': ['error', { allowAllPropertiesOnSameLine: false }],
  'object-shorthand': 'error',
  'one-var': ['error', 'never'],
  'one-var-declaration-per-line': 'error',
  'operator-assignment': 'off',
  'operator-linebreak': ['error', 'before'],
  'padded-blocks': ['error', 'never'],
  'padding-line-between-statements': [
    'error', {
      blankLine: 'always',
      next: '*',
      prev: 'block-like',
    },
  ],
  'prefer-arrow-callback': 'error',
  'prefer-const': 'error',
  'prefer-destructuring': 'error',
  'prefer-exponentiation-operator': 'error',
  'prefer-named-capture-group': 'off',
  'prefer-numeric-literals': 'off',
  'prefer-object-spread': 'error',
  'prefer-promise-reject-errors': 'error',
  'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'quote-props': ['error', 'consistent-as-needed', { keywords: true }],
  'quotes': ['error', 'single', { avoidEscape: true }],

  'radix': 'error',
  'require-atomic-updates': 'error',
  'require-await': 'off',
  'require-unicode-regexp': 'off',
  'require-yield': 'error',
  'rest-spread-spacing': 'error',
  'semi': 'error',
  'semi-spacing': 'error',
  'semi-style': ['error', 'last'],
  'sort-imports': [
    'error', {
      allowSeparatedGroups: true,
      ignoreCase: true,
    },
  ],

  'sort-vars': 'error',
  'space-before-blocks': [
    'error', {
      classes: 'always',
      functions: 'always',
    },
  ],
  'space-before-function-paren': [
    'error', {
      anonymous: 'never',
      asyncArrow: 'always',
      named: 'never',
    },
  ],
  'space-in-parens': 'error',
  'space-infix-ops': 'error',
  'space-unary-ops': [
    'error', {
      nonwords: false,
      words: true,
    },
  ],
  'spaced-comment': 'error',
  'switch-colon-spacing': 'error',
  'symbol-description': 'error',
  'template-curly-spacing': 'error',
  'template-tag-spacing': 'error',
  'unicode-bom': 'error',

  'use-isnan': 'error',
  'valid-typeof': ['error', { requireStringLiterals: true }],
  'vars-on-top': 'error',
  'wrap-iife': ['error', 'inside'],
  'wrap-regex': 'off',
  'yield-star-spacing': 'error',
  'yoda': ['error', 'never', { exceptRange: true }],
};
